#!/bin/bash

godot=$(which godot)
REPO="https://github.com/gcoop-libre/simonPugliese.git"

echo "*************************************************"
echo "* Exportador de Simon Pugliese para Godot 2.1.5 *"
echo "*************************************************"

while [ -z "$VERSION" ] || [ -z "$EXISTE" ]; do
    echo "Ingresá el numero de versión (release) para exportar:"
    read VERSION
    BRANCH="release/$VERSION"
    # Validamos que exista el branch en el repo
    EXISTE=$( git ls-remote --heads "$REPO" | grep "$BRANCH" )
    if [ -z "$EXISTE" ]
    then
	echo "No existe el branch $BRANCH en el repositorio remoto: $REPO"
    fi
done

echo "Creando directorio para los ejecutables en el directorio padre del repo local."
mkdir -p ../exports-release-"$VERSION"
EXPORT_PATH="../../exports-release-$VERSION"
cd game

# android
echo "Exportando para Android..."
$godot -export "Android" "$EXPORT_PATH/simon-pugliese-v$VERSION.apk"
echo "-------------------------------"

# linux 64
echo "Exportando para Linux 64 en $EXPORT_PATH"
$godot -export "Linux X11" "$EXPORT_PATH/simon-pugliese-linux-64-v$VERSION"
echo "-------------------------------"

# o$x 64
echo "Exportando para OSX 64 en $EXPORT_PATH"
$godot -export "Mac OSX" "$EXPORT_PATH/simon-pugliese-osx-64-v$VERSION"
echo "-------------------------------"

# window$ 64
echo "Exportando para Windows 64 en $EXPORT_PATH"
$godot -export "Windows Desktop" "$EXPORT_PATH/simon-pugliese-windows-64-v$VERSION.exe"
echo "-------------------------------"

# Cambiamos lo necesario para exportar para x86.
sed -i.bkp -E 's/64_bits=true/64_bits=false/g' export.cfg

# linux 32
echo "Exportando para Linux 32 en $EXPORT_PATH"
$godot -export "Linux X11" "$EXPORT_PATH/simon-pugliese-linux-32-v$VERSION"
echo "-------------------------------"

# o$x 32
echo "Exportando para OSX 32 en $EXPORT_PATH"
$godot -export "Mac OSX" "$EXPORT_PATH/simon-pugliese-osx-32-v$VERSION"
echo "-------------------------------"

# window$ 32
echo "Exportando para Windows 32 en $EXPORT_PATH"
$godot -export "Windows Desktop" "$EXPORT_PATH/simon-pugliese-windows-32-v$VERSION.exe"
echo "-------------------------------"

mv export.cfg.bkp export.cfg

echo "Listo!"
echo "Los ejecutables están en $EXPORT_PATH"
