#!/bin/bash

echo "*************************************************"
echo "* Exportador de Simon Pugliese para Godot 2.1.5 *"
echo "*************************************************"

godot=$(which godot)
REPO="https://github.com/gcoop-libre/simonPugliese.git"

while [ -z "$VERSION" ] && [ -z "$EXISTE" ]; do
    echo "Ingresá el numero de versión (release) para exportar:"
    read VERSION
done

echo "Creando directorio para los ejecutables en el directorio padre del repo."
mkdir -p ../exports-release-"$VERSION"
EXPORT_PATH="../../exports-release-$VERSION"
cd game

# android
echo "Exportando para Android..."
$godot -export "Android" "$EXPORT_PATH/simon-pugliese-v$VERSION.apk"
echo "-------------------------------"

# linux 64
echo "Exportando para Linux 64 en $EXPORT_PATH"
$godot -export "Linux X11" "$EXPORT_PATH/simon-pugliese-linux-64-v$VERSION"
echo "-------------------------------"

# o$x 64
echo "Exportando para OSX 64 en $EXPORT_PATH"
$godot -export "Mac OSX" "$EXPORT_PATH/simon-pugliese-osx-64-v$VERSION"
echo "-------------------------------"

# window$ 64
echo "Exportando para Windows 64 en $EXPORT_PATH"
$godot -export "Windows Desktop" "$EXPORT_PATH/simon-pugliese-windows-64-v$VERSION.exe"
echo "-------------------------------"

# Cambiamos lo necesario para exportar para x86.
sed -i -E 's/bits_mode=1/bits_mode=2/g' export.cfg
sed -i -E 's/64_bits=true/64_bits=false/g' export.cfg

# linux 32
echo "Exportando para Linux 32 en $EXPORT_PATH"
$godot -export "Linux X11" "$EXPORT_PATH/simon-pugliese-linux-32-v$VERSION"
echo "-------------------------------"

# o$x 32
echo "Exportando para OSX 32 en $EXPORT_PATH"
$godot -export "Mac OSX" "$EXPORT_PATH/simon-pugliese-osx-32-v$VERSION"
echo "-------------------------------"

# window$ 32
echo "Exportando para Windows 32 en $EXPORT_PATH"
$godot -export "Windows Desktop" "$EXPORT_PATH/simon-pugliese-windows-32-v$VERSION.exe"
echo "-------------------------------"

git checkout .

echo "Listo!"
echo "Los ejecutables están en ~/exports"
